### ISSUE TITLE
License

### ISSUE THREAD

**Issue by tamagusko** [jest-uc/portugal-em-chamas#2]
We have to review the modules and check which license to use. I always prefer more permissive licenses, like MIT/Apache.

**Comment by vinicius-cleves** [comment]
@tamagusko I talked with you about MIT, but I was reviewing CC BY-SA and I like the idea of requiring credits. What do you think?

**Comment by vinicius-cleves** [comment]
You also linked this license together with Apache on the badges on readme in the PR I merged earlier. I think we should adopt only one license.

**Comment by tamagusko** [comment]
Yes, we need to use only one. As far as I know CC BY-SA is not recommended for software. What do you think of GPLv3?

**Comment by vinicius-cleves** [comment]
GPLv3 also doesn't seem to enforce acknowledgement of credits. I haven't found any that does such a thing other than from CC. I will rest on MIT for the simplicity then.

**Comment by vinicius-cleves** [comment]
Is your PR with MIT still valid? Also please remove the badge with CC BY-SA from readme on the PR.

**Comment by tamagusko** [comment]
I will fix and send again! Thanks!
